Migrate tests to test starter approach
SAP-samples/ui5-typescript-helloworld pull request #29
Opened 2024-12-09 12:58 UTC by d3xter666

JIRA: CPOUI5FOUNDATION-968

2024-12-10 12:16 UTC, d3xter666 commented
Hi @KlattG ,

Would you take a look at the changes in README.md?

Cheers

2024-12-10 12:46 UTC, akudev approved these changes

2024-12-10 15:05 UTC, KlattG requested changes

2024-12-10 15:05 UTC, KlattG commented on README.md
> +#### The entry point for Unit tests
```suggestion
#### The entry point for unit tests
```

2024-12-10 15:05 UTC, KlattG commented on README.md
> +Just like for the unit tests, [`webapp/test/testsuite.qunit.html`](webapp/test/testsuite.qunit.html) is the entry point for running the OPA tests, which loads the list of journeys configured in [`web
```suggestion
Just like for the unit tests, [`webapp/test/testsuite.qunit.html`](webapp/test/testsuite.qunit.html) is the entry point for running the OPA tests, which loads the list of journeys configured in [`webapp/test/integration/opaTests.qunit.ts`](webapp/test/integration/opaTests.qunit.ts). Select the **integration/opaTests** option to run the OPA tests in a separate window or use the following URL: `/test/Test.qunit.html?testsuite=test-resources/ui5/typescript/helloworld/testsuite.qunit&test=integration/opaTests`
```

2024-12-10 15:05 UTC, KlattG commented on README.md
> +[`webapp/test/unit/unitTests.qunit.ts`](webapp/test/unit/unitTests.qunit.ts) imports all test files, which can be done in a very clean way thanks to the ES6 module imports.
```suggestion
The [`webapp/test/unit/unitTests.qunit.ts`](webapp/test/unit/unitTests.qunit.ts) script imports all test files. Thanks to the ES6 module imports, this is done in a very clean way.
```

2024-12-10 15:05 UTC, KlattG commented on README.md
> +From this entry point, you can choose to run either unit or integration tests. When the **unit/unitTests** link is selected, the UI5 framework is launched, and it loads the list of test cases specifi
```suggestion
From this entry point, you can choose whether to run either unit or integration tests. When the **unit/unitTests** link is selected, the UI5 framework is launched. It then loads the list of test cases specified in [`webapp/test/unit/unitTests.qunit.ts`](webapp/test/unit/unitTests.qunit.ts). A shortcut to launch the unit tests directly is `/test/Test.qunit.html?testsuite=test-resources/ui5/typescript/helloworld/testsuite.qunit&test=unit/unitTests`
```

2024-12-11 08:39 UTC, KlattG approved these changes
LGTM

2024-12-11 10:24 UTC, merged

2024-12-11 10:24 UTC, akudev commented
Thanks!