Use ui5-test-starter instead of deprecated karma
SAP-samples/ui5-typescript-helloworld pull request #31
Opened 2024-12-27 16:08 UTC by akudev

WIP

2024-12-27 16:14 UTC, akudev commented
Open:
- documentation needs to be adapted
- `--port 8081` doesn't seem to do anything reasonable

2025-01-10 13:01 UTC, arnaudbuchholz-sap approved these changes
I confirm that using `--port 8081` is useless if you don't intend to use it. `ui5-test-runner` would allocated a random free port to receive updates from the tests.

For documentation, feel free to push a PR to `ui5-test-runner`

2025-02-04 15:28 UTC, akudev commented
Hi @arnaudbuchholz-sap and @petermuessig, I have now also adapted all documentation. (Which led to some further improvements/fixes in the code). Please have another look, as we want to
1. replace the `main` branch of this repo with this content later to make testing an integral part (this will require some syncing of content updates back and forth, so I will do it in a separate step)
2. adapt the outdated Easy-UI5 templates according to this code, especially the test code and config

2025-02-05 12:34 UTC, ArnaudBuchholz requested changes
You can improve a bit the use of `ui5-test-runner`

2025-02-05 12:34 UTC, ArnaudBuchholz commented on package.json
> +    "test-ui5": "start-server-and-test start-coverage http://localhost:8080 test-runner-coverage",
2 things :
* The `--port` option is useless unless you want to monitor the progress. It may be confusing for people looking at it
* `ui5-test-runner` now offers the `--start` option which allows you to eliminate `start-server-and-test` 😄

2025-02-05 14:23 UTC, akudev commented on package.json
> +    "test-ui5": "start-server-and-test start-coverage http://localhost:8080 test-runner-coverage",
Done, thanks!

2025-02-05 14:33 UTC, ArnaudBuchholz approved these changes

2025-02-10 10:33 UTC, petermuessig approved these changes

2025-02-10 10:40 UTC, merged